version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    container_name: emails-service-app
    hostname: emails-service-app
    volumes:
      - ./:/app
    ports:
      - 3004:3004
    networks:
      - skufspace-network
    environment:
      - PORT=3004
      - DEFAULT_LANG=ru
      - SKUFSPACE_URL=https://example.com
      - SKUFSPACE_TG=SkufspaceSupportBot
      - SKUFSPACE_EMAIL=hello@example.com
      - INTERAPP_TOKEN=interapp_token


networks:
  skufspace-network:
    external: true