export enum NotificationActions {
  // TODO: unite to one event with additional meta: { expiresAt: [1, 7, 0, -1] }
  SUBSCRIPTIONS_EXPIRATION_IN_7_DAYS = 'SUBSCRIPTIONS_EXPIRATION_IN_7_DAYS', // 21
  SUBSCRIPTIONS_EXPIRATION_IN_3_DAYS = 'SUBSCRIPTIONS_EXPIRATION_IN_3_DAYS', // 22
  SUBSCRIPTIONS_EXPIRATION_IN_1_DAYS = 'SUBSCRIPTIONS_EXPIRATION_IN_1_DAYS', // 23
  SUBSCRIPTIONS_EXPIRED = 'SUBSCRIPTIONS_EXPIRED', // 24

  //
  SUBSCRIPTIONS_PROMO_EXPIRED = 'SUBSCRIPTIONS_PROMO_EXPIRED', //20
  SUBSCRIPTIONS_TARIFF_OVER_80 = 'SUBSCRIPTIONS_TARIFF_OVER_80', // 26

  COURSES_NEW_AVAILABLE = 'COURSES_NEW_AVAILABLE', // 5
  COURSES_NEW_LESSONS_ADDED = 'COURSES_NEW_LESSONS_ADDED', // 4
  COURSES_NEW_LESSON_AVAILABLE = 'COURSES_NEW_LESSON_AVAILABLE', // 8
  COURSES_NEW_MODULE_AVAILABLE = 'COURSES_NEW_MODULE_AVAILABLE', // 8
  COURSES_RESTRICTED = 'COURSES_RESTRICTED', // 6
  COURSES_EXPIRED = 'COURSES_EXPIRED', // 7
  COURSES_WEBINAR_COMING = 'COURSES_WEBINAR_COMING', // 9
  COURSES_WEBINAR_STARTED = 'COURSES_WEBINAR_STARTED', // 10
  COURSES_GROUP_PLACES_ARE_OVER = 'COURSES_GROUP_PLACES_ARE_OVER', // 12
  COURSES_STUDENT_COMPLETED_COURSE = 'COURSES_STUDENT_COMPLETED_COURSE', // 13

  HOMEWORKS_STUDENT_SENT = 'HOMEWORKS_STUDENT_SENT', // 2
  HOMEWORKS_TUTOR_SENT = 'HOMEWORKS_TUTOR_SENT', // 3

  BILLING_STUDENT_PAID_FOR_COURSE = 'BILLING_STUDENT_PAID_FOR_COURSE', // 15
  BILLING_VERIFIED = 'BILLING_VERIFIED', // 16
  BILLING_NOT_VERIFIED = 'BILLING_NOT_VERIFIED', // 17
  BILLING_WITHDRAWAL_ACCEPTED = 'BILLING_WITHDRAWAL_ACCEPTED', // 18
  BILLING_WITHDRAWAL_REJECTED = 'BILLING_WITHDRAWAL_REJECTED', // 19
  BILLING_PAYMENT_FAILURE = 'BILLING_PAYMENT_FAILURE', // 25

  CHAT_WAITING_FOR_ANSWER_OVER_24_HOURS = 'CHAT_WAITING_FOR_ANSWER_OVER_24_HOURS', //14

  AFFIILIATE_VERIFIED = 'AFFIILIATE_VERIFIED', // 27.1
  AFFIILIATE_NOT_VERIFIED = 'AFFIILIATE_NOT_VERIFIED', // 27.2
  AFFIILIATE_WITHDRAWAL_ACCEPTED = 'AFFIILIATE_WITHDRAWAL_ACCEPTED', // 27.3
  AFFIILIATE_WITHDRAWAL_REJECTED = 'AFFIILIATE_WITHDRAWAL_REJECTED', // 27.4
  AFFIILIATE_GOT_PAYMENT_BY_LINK = 'AFFIILIATE_GOT_PAYMENT_BY_LINK', // 27.5
  AFFIILIATE_GOLD_STATUS_REACHED = 'AFFIILIATE_GOLD_STATUS_REACHED', // 27.6
}
